# Generated by Django 3.0.5 on 2021-04-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='roll_no',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
